default: &default
  adapter: postgis
  prepared_statements: false
  encoding: unicode
  pool: 8
  schema_search_path: public,postgis

development:
  <<: *default
  database: 'karir_development'
  host: localhost
  port: 5555
  username: postgres
  password: password
